name: Feature request
description: Suggest an improvement
body:
  - type: textarea
    attributes:
      label: What would you like to do?
      description: Explain the use case and expected behavior.
    validations:
      required: true
