#pragma once
// Self-contained: captive browsers need no internet or external assets.
static const char readerWebPage[]=R"INKWEB(<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>InkReader · Files</title>
<style>
:root{font:16px system-ui,sans-serif;color:#25302b;background:#f2f3ed}*{box-sizing:border-box}body{margin:0}main{max-width:920px;margin:auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;margin-bottom:28px}h1{font-size:30px;letter-spacing:-1px;margin:0}small,.muted{color:#657069}button,.button{background:#235b45;color:white;border:0;border-radius:9px;padding:11px 16px;font:inherit;cursor:pointer}button.secondary{background:#e7ede7;color:#25302b}button.danger{background:#f4e8e5;color:#963e2b}button:disabled{opacity:.45;cursor:default}.card{background:white;border:1px solid #dde3da;border-radius:16px;padding:20px;margin-bottom:18px;box-shadow:0 4px 18px #203b2010}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.spread{justify-content:space-between}#drop{border:2px dashed #c2d3c4;text-align:center;padding:28px;background:#f7faf5;border-radius:12px}#drop.over{border-color:#235b45;background:#e7f2e6}#drop p{margin:8px}select,input{font:inherit;max-width:100%;border:1px solid #c7d1c7;border-radius:8px;padding:10px}progress{width:100%;height:9px;accent-color:#235b45}#message{min-height:24px;margin:12px 0;overflow-wrap:anywhere}.error{color:#963e2b}.file{display:grid;grid-template-columns:1fr auto;gap:12px;padding:15px 0;border-bottom:1px solid #edf0e9}.file:last-child{border:0}.name{overflow-wrap:anywhere;text-align:start}.file button{padding:7px 10px;font-size:14px}.path{overflow-wrap:anywhere;font-size:18px;margin:16px 0}details summary{cursor:pointer;font-weight:600}label{display:block;margin:12px 0}footer{text-align:center;font-size:13px;color:#657069;margin:20px}#job{display:none}@media(max-width:550px){main{padding:16px}header{margin-bottom:20px}.card{padding:16px}.file{grid-template-columns:1fr}.actions{justify-content:flex-end}button{padding:10px 12px}}
</style>
<main><header><div><h1>InkReader</h1><small>Your offline reading shelf</small></div><button id="done" class="secondary">Done</button></header>
<section class="card"><div class="row spread"><strong>Reader storage</strong><span id="space" class="muted">Connecting…</span></div><progress id="storage" max="100" value="0"></progress><div id="message" role="status" aria-live="polite"></div>
<div id="drop" tabindex="0"><strong>Add books, PDFs & pictures</strong><p class="muted">Drop or paste files here, or choose from your device.</p><button id="choose">Choose files</button><input id="picker" type="file" multiple hidden accept=".pdf,.epub,.txt,.png,.jpg,.jpeg"><p><small>PDFs become paged image books. Pictures are resized for the screen. Originals stay unchanged.</small></p></div>
<details id="pdfoptions"><summary>PDF / manga import</summary><p class="muted">Rendered locally on this phone or PC, then saved as an image EPUB. Use portrait rotation for tall pages. No internet needed; open this address in a full browser.</p><label>Page layout <select id="pdflayout"><option value="spreads">Split wide spreads automatically</option><option value="full">Whole pages</option><option value="panels">Top / bottom halves (larger lettering)</option></select></label><label>Spread order <select id="pdforder"><option value="rtl">Manga: right half first</option><option value="ltr">Left half first</option></select></label><label><input type="checkbox" id="pdftrim" checked> Trim white margins</label><div class="row"><label>First PDF page <input id="pdffirst" type="number" min="1" value="1" style="width:100px"></label><label>Last PDF page <input id="pdflast" type="number" min="1" placeholder="All" style="width:100px"></label></div><small>128 MiB source / 1000 source pages per import. PDF text is rendered, not reflowed.</small></details>
<div id="job"><p id="jobname" dir="auto"></p><progress id="progress" max="100" value="0"></progress><div class="row spread"><small id="speed"></small><button id="cancel" class="danger">Cancel</button></div></div></section>
<section class="card"><div class="row spread"><strong>Files</strong><div class="row"><button id="up" class="secondary">Up</button><button id="refresh" class="secondary">Refresh</button><button id="folder" class="secondary">New folder</button></div></div><div id="path" class="path" dir="auto">/</div><div id="files"></div></section>
<section id="clock" class="card" hidden><details><summary>Clock Wi-Fi</summary><p class="muted">Optional home network for time synchronization. Separate from this hotspot; saved passwords are never displayed.</p><label>Network name <input id="ssid" maxlength="32" autocomplete="off"></label><label>Password <input id="password" type="password" autocomplete="new-password"></label><div class="row"><button id="saveclock">Save</button><button id="clearclock" class="secondary">Clear clock credentials</button></div></details></section>
<footer>No internet required · Wi-Fi closes after 5 idle minutes.<br>If the sign-in window limits files, open http://192.168.4.1 in your browser.</footer></main>
<script src="/pdf-import.js"></script>
<script>
'use strict';
const $=id=>document.getElementById(id);let token='',path='/',entries=[],requestId=(crypto.getRandomValues(new Uint32Array(1))[0]>>>1)||1,working=false,cancelled=false,lastTouch=0;
const encoder=new TextEncoder(),decoder=new TextDecoder();
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';}
function bytes(n){return n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':n<1073741824?(n/1048576).toFixed(1)+' MB':(n/1073741824).toFixed(1)+' GB';}
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=(n>>>1)^((n&1)?0xedb88320:0);return n>>>0;});
function crcStep(crc,data){for(const b of data)crc=(crc>>>8)^crcTable[(crc^b)&255];return crc>>>0;}
async function rpc(op,body={},binary=false){const payload=body instanceof Uint8Array?body:encoder.encode(JSON.stringify(body));const id=++requestId;let last;
 for(let attempt=0;attempt<3;attempt++){try{const abort=new AbortController();const timer=setTimeout(()=>abort.abort(),120000);let response;try{response=await fetch('/api/op',{method:'POST',headers:{'X-Reader-Token':token,'X-Reader-Operation':String(op),'X-Reader-Request':String(id)},body:payload,signal:abort.signal});}finally{clearTimeout(timer);}const data=new Uint8Array(await response.arrayBuffer());if(!response.ok){const failure=JSON.parse(decoder.decode(data));const error=new Error(failure.error||'Reader rejected the operation');error.permanent=true;throw error;}return binary?data:JSON.parse(decoder.decode(data)||'{}');}catch(error){last=error;if(error.permanent||cancelled)throw error;await new Promise(resolve=>setTimeout(resolve,300*(attempt+1)));}}throw last;
}
function join(name){return path==='/'?'/'+name:path+'/'+name;}
function lock(active){working=active;$('job').style.display=active?'block':'none';for(const id of ['choose','up','refresh','folder'])$(id).disabled=active;}
function job(name,done,total,start){$('jobname').textContent=name;$('progress').value=total?done*100/total:0;const elapsed=(performance.now()-start)/1000,speed=done/Math.max(.01,elapsed);$('speed').textContent=bytes(done)+' / '+bytes(total)+' · '+bytes(speed)+'/s'+(speed?' · '+Math.ceil((total-done)/speed)+'s remaining':'');}
async function browse(){if(working)return;try{const next=[];let cursor=0;do{const page=await rpc(2,{path,cursor});next.push(...page.entries);cursor=page.next;}while(cursor>=0);entries=next.sort((a,b)=>Number(b.directory)-Number(a.directory)||a.name.localeCompare(b.name));$('path').textContent=path;$('up').disabled=path==='/';$('files').replaceChildren();for(const entry of entries){const row=document.createElement('div');row.className='file';const name=document.createElement('button');name.className='secondary name';name.dir='auto';name.textContent=(entry.directory?'▦  ':'▤  ')+entry.name;name.onclick=()=>entry.directory?openFolder(join(entry.name)):download(entry);const actions=document.createElement('div');actions.className='row actions';const size=document.createElement('small');size.textContent=entry.directory?'Folder':bytes(entry.size);actions.append(size);const remove=document.createElement('button');remove.className='danger';remove.textContent='Delete';remove.onclick=async()=>{if(working)return;if(confirm('Delete '+entry.name+'? Folders must be empty.')){try{await rpc(10,{path:join(entry.name)});await browse();}catch(e){message(e.message,true);}}};actions.append(remove);row.append(name,actions);$('files').append(row);}if(!entries.length){$('files').textContent='This folder is empty. Add your first book or picture.';}const space=await rpc(3);$('space').textContent=bytes(space.free)+' free of '+bytes(space.total);$('storage').value=100*(space.total-space.free)/space.total;}catch(e){message(e.message+' · Rejoin the reader Wi-Fi if the session ended.',true);}}
function openFolder(folder){if(working)return;path=folder;browse();}
async function prepare(file){if(/\.pdf$/i.test(file.name))return InkPdf.prepare(file,{layout:$('pdflayout').value,rtl:$('pdforder').value==='rtl',trim:$('pdftrim').checked,first:$('pdffirst').value,last:$('pdflast').value},{cancelled:()=>cancelled,activity:()=>rpc(15),progress:(text,done,total)=>{message(text);$('job').style.display='block';$('jobname').textContent=file.name;$('progress').value=total?100*done/total:0;$('speed').textContent='Preparing locally - original PDF stays on your device';}});if(!/\.(jpe?g|png)$/i.test(file.name))return file;
 const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const scale=Math.min(1,800/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0,canvas.width,canvas.height);const pixels=context.getImageData(0,0,canvas.width,canvas.height).data;let alpha=false;for(let i=3;i<pixels.length;i+=4)if(pixels[i]!==255){alpha=true;break;}const format=alpha?'image/png':'image/jpeg';let quality=.9,blob;
 for(let iteration=0;iteration<14;iteration++){blob=await new Promise(resolve=>canvas.toBlob(resolve,format,quality));if(!blob)throw new Error('Image encoding failed');if(blob.size<1048576)break;if(!alpha&&quality>.5){quality-=.1;}else{const smaller=document.createElement('canvas');smaller.width=Math.max(1,Math.floor(canvas.width*.8));smaller.height=Math.max(1,Math.floor(canvas.height*.8));smaller.getContext('2d').drawImage(canvas,0,0,smaller.width,smaller.height);canvas.width=smaller.width;canvas.height=smaller.height;context.drawImage(smaller,0,0);}}
 if(blob.size>=1048576)throw new Error('Image cannot fit the reader decoder limit');return new File([blob],file.name.replace(/\.[^.]+$/,alpha?'.png':'.jpg'),{type:format});}finally{URL.revokeObjectURL(url);}}
async function uploads(files){if(working||!files.length)return;lock(true);cancelled=false;try{for(const original of files){if(cancelled)break;message('Preparing '+original.name);const file=await prepare(original);if(cancelled)throw new Error('Cancelled');const exists=entries.some(e=>e.name===file.name);if(exists&&!confirm('Replace '+file.name+' on the reader?'))continue;let crc=0xffffffff;for(let offset=0;offset<file.size;offset+=65536){if(cancelled)throw new Error('Cancelled');crc=crcStep(crc,new Uint8Array(await file.slice(offset,offset+65536).arrayBuffer()));}await rpc(4,{path:join(file.name),size:file.size,crc:(~crc)>>>0,overwrite:exists});const start=performance.now();for(let offset=0;offset<file.size;offset+=4096){if(cancelled)throw new Error('Cancelled');const data=new Uint8Array(await file.slice(offset,offset+4096).arrayBuffer()),chunk=new Uint8Array(8+data.length);new DataView(chunk.buffer).setUint32(0,offset,true);new DataView(chunk.buffer).setUint32(4,(~crcStep(0xffffffff,data))>>>0,true);chunk.set(data,8);const ack=await rpc(5,chunk);if(ack.offset!==offset+data.length)throw new Error('Upload acknowledgement mismatch');job(file.name,ack.offset,file.size,start);}message('Verifying '+file.name);await rpc(6);if(!entries.some(entry=>entry.name===file.name))entries.push({name:file.name,directory:false,size:file.size});message('Saved '+file.name);}}catch(e){message(e.message,true);try{await rpc(11);}catch(_){}}finally{lock(false);cancelled=false;await browse();}}
async function download(entry){if(working)return;lock(true);cancelled=false;try{const info=await rpc(7,{path:join(entry.name)}),parts=[];let crc=0xffffffff;const start=performance.now();for(let offset=0;offset<info.size;offset+=4096){if(cancelled)throw new Error('Cancelled');const query=new Uint8Array(8);const view=new DataView(query.buffer);view.setUint32(0,offset,true);view.setUint32(4,Math.min(4096,info.size-offset),true);const chunk=await rpc(8,query,true);if(chunk.length!==4+Math.min(4096,info.size-offset)||new DataView(chunk.buffer).getUint32(0,true)!==offset)throw new Error('Download length mismatch');const data=chunk.slice(4);crc=crcStep(crc,data);parts.push(data);job(entry.name,offset+data.length,info.size,start);}if(((~crc)>>>0)!==info.crc)throw new Error('Download CRC mismatch');const url=URL.createObjectURL(new Blob(parts));const anchor=document.createElement('a');anchor.href=url;anchor.download=entry.name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),60000);message('Downloaded '+entry.name);}catch(e){message(e.message,true);}finally{try{await rpc(11);}catch(_){}lock(false);cancelled=false;}}
$('choose').onclick=()=>$('picker').click();$('picker').onchange=()=>{uploads(Array.from($('picker').files));$('picker').value='';};$('cancel').onclick=()=>{cancelled=true;};$('up').onclick=()=>openFolder(path.substring(0,path.lastIndexOf('/'))||'/');$('refresh').onclick=browse;$('folder').onclick=async()=>{const name=prompt('Folder name');if(!name)return;try{await rpc(9,{path:join(name)});await browse();}catch(e){message(e.message,true);}};$('done').onclick=async()=>{if(working){if(!confirm('Cancel the transfer and return to reading?'))return;cancelled=true;message('Cancelling… Press Done again when the transfer stops.');return;}try{await rpc(12);message('Finished. Reader Wi-Fi is now off; reconnect to your usual network.');}catch(_){message('Reader disconnected. Return to your usual Wi-Fi.');}};
for(const event of ['dragenter','dragover'])$('drop').addEventListener(event,e=>{e.preventDefault();$('drop').classList.add('over');});$('drop').addEventListener('dragleave',()=>$('drop').classList.remove('over'));$('drop').addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('over');uploads(Array.from(e.dataTransfer.files));});document.addEventListener('paste',e=>{const files=Array.from(e.clipboardData?.files||[]);if(files.length){e.preventDefault();uploads(files);}});
for(const event of ['pointerdown','keydown'])document.addEventListener(event,()=>{if(token&&!working&&Date.now()-lastTouch>20000){lastTouch=Date.now();rpc(15).catch(()=>{});}});
$('saveclock').onclick=async()=>{try{await rpc(14,{ssid:$('ssid').value,password:$('password').value});$('password').value='';message('Clock network saved. Open Screensaver after leaving File Transfer.');}catch(e){message(e.message,true);}};$('clearclock').onclick=async()=>{if(!confirm('Clear the clock network?'))return;try{await rpc(14,{clear:true});$('password').value='';message('Clock credentials cleared.');}catch(e){message(e.message,true);}};
(async()=>{try{const response=await fetch('/api/session');const session=await response.json();if(session.product!=='InkReader'||session.api!==1)throw new Error('Unsupported reader');token=session.token;$('clock').hidden=!session.clock;await rpc(1);message('Connected. Choose a book or picture to add.');await browse();}catch(e){message(e.message+' · Open http://192.168.4.1 in a full browser.',true);}})();
</script></html>)INKWEB";
